// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: bot.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBotRequest) Reset() {
	*x = AddBotRequest{}
	mi := &file_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBotRequest) ProtoMessage() {}

func (x *AddBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBotRequest.ProtoReflect.Descriptor instead.
func (*AddBotRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{0}
}

func (x *AddBotRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddBotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBotReply) Reset() {
	*x = AddBotReply{}
	mi := &file_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBotReply) ProtoMessage() {}

func (x *AddBotReply) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBotReply.ProtoReflect.Descriptor instead.
func (*AddBotReply) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{1}
}

func (x *AddBotReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddBotReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RemoveBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBotRequest) Reset() {
	*x = RemoveBotRequest{}
	mi := &file_bot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBotRequest) ProtoMessage() {}

func (x *RemoveBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBotRequest.ProtoReflect.Descriptor instead.
func (*RemoveBotRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveBotRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveBotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBotReply) Reset() {
	*x = RemoveBotReply{}
	mi := &file_bot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBotReply) ProtoMessage() {}

func (x *RemoveBotReply) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBotReply.ProtoReflect.Descriptor instead.
func (*RemoveBotReply) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveBotReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RemoveBotReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_bot_proto protoreflect.FileDescriptor

const file_bot_proto_rawDesc = "" +
	"\n" +
	"\tbot.proto\x12\x02pb\"\x1f\n" +
	"\rAddBotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"9\n" +
	"\vAddBotReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\"\n" +
	"\x10RemoveBotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\x0eRemoveBotReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername2j\n" +
	"\x03Bot\x12,\n" +
	"\x06AddBot\x12\x11.pb.AddBotRequest\x1a\x0f.pb.AddBotReply\x125\n" +
	"\tRemoveBot\x12\x14.pb.RemoveBotRequest\x1a\x12.pb.RemoveBotReplyb\x06proto3"

var (
	file_bot_proto_rawDescOnce sync.Once
	file_bot_proto_rawDescData []byte
)

func file_bot_proto_rawDescGZIP() []byte {
	file_bot_proto_rawDescOnce.Do(func() {
		file_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)))
	})
	return file_bot_proto_rawDescData
}

var file_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bot_proto_goTypes = []any{
	(*AddBotRequest)(nil),    // 0: pb.AddBotRequest
	(*AddBotReply)(nil),      // 1: pb.AddBotReply
	(*RemoveBotRequest)(nil), // 2: pb.RemoveBotRequest
	(*RemoveBotReply)(nil),   // 3: pb.RemoveBotReply
}
var file_bot_proto_depIdxs = []int32{
	0, // 0: pb.Bot.AddBot:input_type -> pb.AddBotRequest
	2, // 1: pb.Bot.RemoveBot:input_type -> pb.RemoveBotRequest
	1, // 2: pb.Bot.AddBot:output_type -> pb.AddBotReply
	3, // 3: pb.Bot.RemoveBot:output_type -> pb.RemoveBotReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bot_proto_init() }
func file_bot_proto_init() {
	if File_bot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_proto_goTypes,
		DependencyIndexes: file_bot_proto_depIdxs,
		MessageInfos:      file_bot_proto_msgTypes,
	}.Build()
	File_bot_proto = out.File
	file_bot_proto_goTypes = nil
	file_bot_proto_depIdxs = nil
}
